/* tslint:disable */
/* eslint-disable */
/**
 * Docs
 * API
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface AddressCreateDto
 */
export interface AddressCreateDto {
    /**
     * 
     * @type {string}
     * @memberof AddressCreateDto
     */
    userId: string;
    /**
     * 
     * @type {string}
     * @memberof AddressCreateDto
     */
    zipcode: string;
    /**
     * 
     * @type {string}
     * @memberof AddressCreateDto
     */
    neighborhood: string;
    /**
     * 
     * @type {string}
     * @memberof AddressCreateDto
     */
    state: string;
    /**
     * 
     * @type {string}
     * @memberof AddressCreateDto
     */
    city: string;
    /**
     * 
     * @type {string}
     * @memberof AddressCreateDto
     */
    street: string;
    /**
     * 
     * @type {number}
     * @memberof AddressCreateDto
     */
    number: number;
    /**
     * 
     * @type {string}
     * @memberof AddressCreateDto
     */
    complement: string;
}
