/* tslint:disable */
/* eslint-disable */
/**
 * Docs
 * API
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface LoginAuthDto
 */
export interface LoginAuthDto {
    /**
     * 
     * @type {string}
     * @memberof LoginAuthDto
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof LoginAuthDto
     */
    password: string;
}
